version: 0.0
os: linux
files:
  - source: /
    destination: /home/abdelali/devopspipeline
hooks:
    # ApplicationStop:
    #    - location: scripts/stop-container.sh
    #      timeout: 300
    #      runas: abdelali
    # BeforeInstall:
    #    - location: scripts/stop-container.sh
    #      timeout: 300
    #      runas: abdelali
    AfterInstall:
       - location: scripts/stop-containers.sh
         timeout: 300
         runas: root
    ApplicationStart:
       - location: scripts/start-containers.sh
         timeout: 300
         runas: abdelali

    
       
#   BeforeInstall:
#     - location: scripts/UnzipResourceBundle.sh
#   AfterInstall:
#     - location: scripts/RunResourceTests.sh
#       timeout: 300
#   ApplicationStart:
#     - location: scripts/RunFunctionalTests.sh
#       timeout: 300
#       runas: root
#   ValidateService:
#     - location: scripts/MonitorService.sh
#       timeout: 300
#       runas: ubuntu